post_install() {
  echo "Please add 'nvidia' to the HOOKs array in /etc/mkinitcpio.conf, and 'linux-headers' to the SyncFirst array in /etc/pacman.conf to enable the automatic modules compilation. For custom kernels, please ensure the corresponding headers are uppdated before generating the initramfs."
  dkms install -m nvidia/${1%-*}
}

pre_upgrade() {
  pre_remove ${2}
}

post_upgrade() {
  post_install ${1}
}

pre_remove() {
  dkms remove -m nvidia/${1%-*} --all
}

# vim: ts=2 sw=2 et:
