#!/bin/bash

installpkg() {
  cd $1
  makepkg -cfis
  cd ..
}

install() {
  for pkg in granite-bzr libdbusmenu libdbusmenu-gtk3 libindicate sqlheavy-git pantheon-terminal-bzr noise-bzr; do
    installpkg $pkg
  done
}

update() {
  for pkg in granite-bzr sqlheavy-git pantheon-terminal-bzr noise-bzr; do
    installpkg $pkg
  done
}

if [[ $1 == "install" ]]; then
  if [[ $2 == "" ]]; then
    install
  else
    echo ${@#install}
    for pkg in ${@#install}; do
      echo "Installing $pkg"
      installpkg $pkg
    done
  fi
fi

if [[ $1 == "update" ]]; then
  if [[ $2 == "" ]]; then
    install
  else
    echo ${@#update}
    for pkg in ${@#update}; do
      echo "Updating $pkg"
      installpkg $pkg
    done
  fi
fi
