#!/bin/sh

for pkg in granite-bzr libpantheon-bzr contractor-bzr webcontracts-bzr plank-bzr wingpanel-bzr slingshot-launcher-bzr switchboard-bzr switchboard-plug-{pantheon-shell,keyboard,power,elementary-tweaks,default-applications,about}-bzr pantheon-files-bzr noise-bzr pantheon-terminal-bzr pantheon-wallpaper-bzr cerbere-bzr gala-bzr gtk-theme-elementary4.0-bzr elementary-icon-theme-bzr elementary-icons-thirdparty-bzr; do
  cd $pkg
  makepkg -cis
  cd ..
done
