#!/bin/sh

for repo in community pantheon unsupported personal; do
  find $repo -type d -name pkg -exec rm -rf {} +
  find $repo -type d -name src -exec rm -rf {} +
  find $repo -name *.tar.xz -delete
  find $repo -name *.tar.xz.sig -delete
  find $repo -name *.log -delete
done

# vim: ts=2 sw=2 et:
