diff -rupN ultrastardx.orig/src/Makefile.in ultrastardx/src/Makefile.in
--- ultrastardx.orig/src/Makefile.in	2014-07-21 18:49:17.332846300 +0200
+++ ultrastardx/src/Makefile.in	2014-07-21 18:49:27.136921400 +0200
@@ -122,7 +122,7 @@ endif
 
 LIBS       ?= @LIBS@
 LDFLAGS    ?= @LDFLAGS@
-linkflags  := -L/usr/lib $(LDFLAGS) $(sort $(LIBS))
+linkflags  := $(LDFLAGS) $(sort $(LIBS)) -L/usr/lib
 ifneq ($(linkflags),)
 PLINKFLAGS := -k"$(linkflags)"
 endif
